### ISSUE TITLE
Wrong OPTIMADEStructureAttributes datamodel

### ISSUE THREAD

**Issue by jesper-friis** [SINTEF/oteapi-optimade#164]
There are many issues in the OPTIMADEStructureAttributes datamodel.

`nelements` is used both as a dimension and as a property. It can only be one of them, in this `nelements`.

Same with `nsites`.

`elements_rations` is not well-defined. The description should describe how this array constructed?

**Comment by CasperWA** [comment]
It should be able to be both as `nelements` is a property of the OPTIMADE data model. But I suppose `dimensions` will be a property of any model instance in any case - it can be put there then.

The definitions are taken verbatim from the specification - however, it may be minimized in certain cases. Since the OPTIMADE specification does not support data creation, but only retrieval, I don't see an immediate issue with this problem. The main goal of the OTEAPI OPTIMADE plugin is to enable users to _retrieve_ structures (and possibly other resources) from a materials database throught he OPTIMADE REST API.

**Comment by jesper-friis** [comment]
No. Dimensions and properties cannot have the same name. For two reasons:
- the Python interface makes them available as attributes. If `nelements` is both a dimension and a property, `inst.nelements` is ambiguous. This is the reason that the Musicode demo is failing.
- the C code generator will create a C-struct containing both dimensions and properties. If they share name, you will get duplicated fields and the compilation will fail.

**Comment by CasperWA** [comment]
> I get issues when removing the properties from "properties", keeping them only in "dimensions" (see [this test run](https://github.com/SINTEF/oteapi-optimade/actions/runs/6610333131/job/17952051278?pr=169#step:5:112)). What is the DLite way of dealing with this then?

I think I fixed it.
